import {
    parseNumber,
    formatTime,
    getOSAndBrowser,
    createFileSections,
    createPreview,
    formatDate,
    formatAMPM,
    createThumbnail,
    isCloseToBottom,
    handleHistoryFilePath,
    getInitials,
    unixToDate,
    formatBytes,
    validateEmail,
    handleLinks,
    createFilesList,
} from './common';
import {
    encryptBlob,
    decryptBlob,
    pbEncrypt,
    pbDecrypt,
    encryptFileVault,
    decryptFileVault,
    encryptTextVault,
    decryptTextVault,
    createPasswordHash,
} from './cryptography';

import secureStorage from './secureStorage';

export {
    parseNumber,
    formatTime,
    getOSAndBrowser,
    encryptBlob,
    decryptBlob,
    pbEncrypt,
    pbDecrypt,
    encryptFileVault,
    decryptFileVault,
    createFileSections,
    createPreview,
    formatDate,
    formatAMPM,
    createThumbnail,
    isCloseToBottom,
    handleHistoryFilePath,
    getInitials,
    unixToDate,
    formatBytes,
    validateEmail,
    encryptTextVault,
    decryptTextVault,
    createPasswordHash,
    handleLinks,
    createFilesList,
    secureStorage,
};
