export const countryCodes = [
    {
        title: 'A',
        data: [
            {name: 'Afghanistan', dialCode: '+93', code: 'AF'},
            {name: 'Albania', dialCode: '+355', code: 'AL'},
            {name: 'Algeria', dialCode: '+213', code: 'DZ'},
            {name: 'American Samoa', dialCode: '+1684', code: 'AS'},
            {name: 'Andorra', dialCode: '+376', code: 'AD'},
            {name: 'Angola', dialCode: '+244', code: 'AO'},
            {name: 'Anguilla', dialCode: '+1264', code: 'AI'},
            {name: 'Antarctica', dialCode: '+672', code: 'AQ'},
            {name: 'Antigua and Barbuda', dialCode: '+1268', code: 'AG'},
            {name: 'Argentina', dialCode: '+54', code: 'AR'},
            {name: 'Armenia', dialCode: '+374', code: 'AM'},
            {name: 'Aruba', dialCode: '+297', code: 'AW'},
            {name: 'Australia', dialCode: '+61', code: 'AU'},
            {name: 'Austria', dialCode: '+43', code: 'AT'},
            {name: 'Azerbaijan', dialCode: '+994', code: 'AZ'},
        ],
    },
    {
        title: 'B',
        data: [
            {name: 'Bahamas', dialCode: '+1242', code: 'BS'},
            {name: 'Bahrain', dialCode: '+973', code: 'BH'},
            {name: 'Bangladesh', dialCode: '+880', code: 'BD'},
            {name: 'Barbados', dialCode: '+1246', code: 'BB'},
            {name: 'Belarus', dialCode: '+375', code: 'BY'},
            {name: 'Belgium', dialCode: '+32', code: 'BE'},
            {name: 'Belize', dialCode: '+501', code: 'BZ'},
            {name: 'Benin', dialCode: '+229', code: 'BJ'},
            {name: 'Bermuda', dialCode: '+1441', code: 'BM'},
            {name: 'Bhutan', dialCode: '+975', code: 'BT'},
            {name: 'Bolivia', dialCode: '+591', code: 'BO'},
            {name: 'Bosnia and Herzegovina', dialCode: '+387', code: 'BA'},
            {name: 'Botswana', dialCode: '+267', code: 'BW'},
            {name: 'Bouvet Island', dialCode: '+47', code: 'BV'},
            {name: 'Brazil', dialCode: '+55', code: 'BR'},
            {name: 'British Indian Ocean Territory', dialCode: '+246', code: 'IO'},
            {name: 'Brunei Darussalam', dialCode: '+673', code: 'BN'},
            {name: 'Bulgaria', dialCode: '+359', code: 'BG'},
            {name: 'Burkina Faso', dialCode: '+226', code: 'BF'},
            {name: 'Burundi', dialCode: '+257', code: 'BI'},
        ],
    },
    {
        title: 'C',
        data: [
            {name: 'Cambodia', dialCode: '+855', code: 'KH'},
            {name: 'Cameroon', dialCode: '+237', code: 'CM'},
            {name: 'Canada', dialCode: '+1', code: 'CA'},
            {name: 'Cape Verde', dialCode: '+238', code: 'CV'},
            {name: 'Cayman Islands', dialCode: '+ 345', code: 'KY'},
            {name: 'Central African Republic', dialCode: '+236', code: 'CF'},
            {name: 'Chad', dialCode: '+235', code: 'TD'},
            {name: 'Chile', dialCode: '+56', code: 'CL'},
            {name: 'China', dialCode: '+86', code: 'CN'},
            {name: 'Christmas Island', dialCode: '+61', code: 'CX'},
            {name: 'Colombia', dialCode: '+57', code: 'CO'},
            {name: 'Comoros', dialCode: '+269', code: 'KM'},
            {name: 'Congo - Brazzaville', dialCode: '+242', code: 'CG'},
            {name: 'Congo - Kinshasa', dialCode: '+243', code: 'CD'},
            {name: 'Cook Islands', dialCode: '+682', code: 'CK'},
            {name: 'Costa Rica', dialCode: '+506', code: 'CR'},
            {name: "Cote d'Ivoire", dialCode: '+225', code: 'CI'},
            {name: 'Croatia', dialCode: '+385', code: 'HR'},
            {name: 'Cuba', dialCode: '+53', code: 'CU'},
            {name: 'Cyprus', dialCode: '+357', code: 'CY'},
            {name: 'Czech Republic', dialCode: '+420', code: 'CZ'},
        ],
    },
    {
        title: 'D',
        data: [
            {name: 'Denmark', dialCode: '+45', code: 'DK'},
            {name: 'Djibouti', dialCode: '+253', code: 'DJ'},
            {name: 'Dominica', dialCode: '+1767', code: 'DM'},
            {name: 'Dominican Republic', dialCode: '+1849', code: 'DO'},
        ],
    },
    {
        title: 'E',
        data: [
            {name: 'Ecuador', dialCode: '+593', code: 'EC'},
            {name: 'Egypt', dialCode: '+20', code: 'EG'},
            {name: 'El Salvador', dialCode: '+503', code: 'SV'},
            {name: 'Equatorial Guinea', dialCode: '+240', code: 'GQ'},
            {name: 'Eritrea', dialCode: '+291', code: 'ER'},
            {name: 'Estonia', dialCode: '+372', code: 'EE'},
            {name: 'Ethiopia', dialCode: '+251', code: 'ET'},
        ],
    },
    {
        title: 'F',
        data: [
            {name: 'Falkland Islands', dialCode: '+500', code: 'FK'},
            {name: 'Faroe Islands', dialCode: '+298', code: 'FO'},
            {name: 'Fiji', dialCode: '+679', code: 'FJ'},
            {name: 'Finland', dialCode: '+358', code: 'FI'},
            {name: 'France', dialCode: '+33', code: 'FR'},
            {name: 'French Guiana', dialCode: '+594', code: 'GF'},
            {name: 'French Polynesia', dialCode: '+689', code: 'PF'},
        ],
    },
    {
        title: 'G',
        data: [
            {name: 'Gabon', dialCode: '+241', code: 'GA'},
            {name: 'Gambia', dialCode: '+220', code: 'GM'},
            {name: 'Georgia', dialCode: '+995', code: 'GE'},
            {name: 'Germany', dialCode: '+49', code: 'DE'},
            {name: 'Ghana', dialCode: '+233', code: 'GH'},
            {name: 'Gibraltar', dialCode: '+350', code: 'GI'},
            {name: 'Greece', dialCode: '+30', code: 'GR'},
            {name: 'Greenland', dialCode: '+299', code: 'GL'},
            {name: 'Grenada', dialCode: '+1473', code: 'GD'},
            {name: 'Guadeloupe', dialCode: '+590', code: 'GP'},
            {name: 'Guam', dialCode: '+1671', code: 'GU'},
            {name: 'Guatemala', dialCode: '+502', code: 'GT'},
            {name: 'Guernsey', dialCode: '+44', code: 'GG'},
            {name: 'Guinea', dialCode: '+224', code: 'GN'},
            {name: 'Guinea-Bissau', dialCode: '+245', code: 'GW'},
            {name: 'Guyana', dialCode: '+592', code: 'GY'},
        ],
    },
    {
        title: 'H',
        data: [
            {name: 'Haiti', dialCode: '+509', code: 'HT'},
            {name: 'Honduras', dialCode: '+504', code: 'HN'},
            {name: 'Hong Kong', dialCode: '+852', code: 'HK'},
            {name: 'Hungary', dialCode: '+36', code: 'HU'},
        ],
    },
    {
        title: 'I',
        data: [
            {name: 'Iceland', dialCode: '+354', code: 'IS'},
            {name: 'India', dialCode: '+91', code: 'IN'},
            {name: 'Indonesia', dialCode: '+62', code: 'ID'},
            {name: 'Iran', dialCode: '+98', code: 'IR'},
            {name: 'Iraq', dialCode: '+964', code: 'IQ'},
            {name: 'Ireland', dialCode: '+353', code: 'IE'},
            {name: 'Isle of Man', dialCode: '+44', code: 'IM'},
            {name: 'Israel', dialCode: '+972', code: 'IL'},
            {name: 'Italy', dialCode: '+39', code: 'IT'},
        ],
    },
    {
        title: 'J',
        data: [
            {name: 'Jamaica', dialCode: '+1876', code: 'JM'},
            {name: 'Japan', dialCode: '+81', code: 'JP'},
            {name: 'Jersey', dialCode: '+44', code: 'JE'},
            {name: 'Jordan', dialCode: '+962', code: 'JO'},
        ],
    },
    {
        title: 'K',
        data: [
            {name: 'Kazakhstan', dialCode: '+7', code: 'KZ'},
            {name: 'Kenya', dialCode: '+254', code: 'KE'},
            {name: 'Kiribati', dialCode: '+686', code: 'KI'},
            {name: 'Kosovo', dialCode: '+383', code: 'XK'},
            {name: 'Kuwait', dialCode: '+965', code: 'KW'},
            {name: 'Kyrgyzstan', dialCode: '+996', code: 'KG'},
        ],
    },
    {
        title: 'L',
        data: [
            {name: 'Laos', dialCode: '+856', code: 'LA'},
            {name: 'Latvia', dialCode: '+371', code: 'LV'},
            {name: 'Lebanon', dialCode: '+961', code: 'LB'},
            {name: 'Lesotho', dialCode: '+266', code: 'LS'},
            {name: 'Liberia', dialCode: '+231', code: 'LR'},
            {name: 'Libya', dialCode: '+218', code: 'LY'},
            {name: 'Liechtenstein', dialCode: '+423', code: 'LI'},
            {name: 'Lithuania', dialCode: '+370', code: 'LT'},
            {name: 'Luxembourg', dialCode: '+352', code: 'LU'},
        ],
    },
    {
        title: 'M',
        data: [
            {name: 'Macao', dialCode: '+853', code: 'MO'},
            {name: 'Macedonia', dialCode: '+389', code: 'MK'},
            {name: 'Madagascar', dialCode: '+261', code: 'MG'},
            {name: 'Malawi', dialCode: '+265', code: 'MW'},
            {name: 'Malaysia', dialCode: '+60', code: 'MY'},
            {name: 'Maldives', dialCode: '+960', code: 'MV'},
            {name: 'Mali', dialCode: '+223', code: 'ML'},
            {name: 'Malta', dialCode: '+356', code: 'MT'},
            {name: 'Marshall Islands', dialCode: '+692', code: 'MH'},
            {name: 'Martinique', dialCode: '+596', code: 'MQ'},
            {name: 'Mauritania', dialCode: '+222', code: 'MR'},
            {name: 'Mauritius', dialCode: '+230', code: 'MU'},
            {name: 'Mayotte', dialCode: '+262', code: 'YT'},
            {name: 'Mexico', dialCode: '+52', code: 'MX'},
            {name: 'Micronesia', dialCode: '+691', code: 'FM'},
            {name: 'Moldova', dialCode: '+373', code: 'MD'},
            {name: 'Monaco', dialCode: '+377', code: 'MC'},
            {name: 'Mongolia', dialCode: '+976', code: 'MN'},
            {name: 'Montenegro', dialCode: '+382', code: 'ME'},
            {name: 'Montserrat', dialCode: '+1664', code: 'MS'},
            {name: 'Morocco', dialCode: '+212', code: 'MA'},
            {name: 'Mozambique', dialCode: '+258', code: 'MZ'},
            {name: 'Myanmar', dialCode: '+95', code: 'MM'},
        ],
    },
    {
        title: 'N',
        data: [
            {name: 'Namibia', dialCode: '+264', code: 'NA'},
            {name: 'Nauru', dialCode: '+674', code: 'NR'},
            {name: 'Nepal', dialCode: '+977', code: 'NP'},
            {name: 'Netherlands', dialCode: '+31', code: 'NL'},
            {name: 'Netherlands Antilles', dialCode: '+599', code: 'AN'},
            {name: 'New Caledonia', dialCode: '+687', code: 'NC'},
            {name: 'New Zealand', dialCode: '+64', code: 'NZ'},
            {name: 'Nicaragua', dialCode: '+505', code: 'NI'},
            {name: 'Niger', dialCode: '+227', code: 'NE'},
            {name: 'Nigeria', dialCode: '+234', code: 'NG'},
            {name: 'Niue', dialCode: '+683', code: 'NU'},
            {name: 'Norfolk Island', dialCode: '+672', code: 'NF'},
            {name: 'North Korea', dialCode: '+850', code: 'KP'},
            {name: 'Northern Mariana Islands', dialCode: '+1670', code: 'MP'},
            {name: 'Norway', dialCode: '+47', code: 'NO'},
        ],
    },
    {title: 'O', data: [{name: 'Oman', dialCode: '+968', code: 'OM'}]},
    {
        title: 'P',
        data: [
            {name: 'Pakistan', dialCode: '+92', code: 'PK'},
            {name: 'Palau', dialCode: '+680', code: 'PW'},
            {name: 'Palestine', dialCode: '+970', code: 'PS'},
            {name: 'Panama', dialCode: '+507', code: 'PA'},
            {name: 'Papua New Guinea', dialCode: '+675', code: 'PG'},
            {name: 'Paraguay', dialCode: '+595', code: 'PY'},
            {name: 'Peru', dialCode: '+51', code: 'PE'},
            {name: 'Philippines', dialCode: '+63', code: 'PH'},
            {name: 'Pitcairn', dialCode: '+64', code: 'PN'},
            {name: 'Poland', dialCode: '+48', code: 'PL'},
            {name: 'Portugal', dialCode: '+351', code: 'PT'},
            {name: 'Puerto Rico', dialCode: '+1939', code: 'PR'},
        ],
    },
    {title: 'Q', data: [{name: 'Qatar', dialCode: '+974', code: 'QA'}]},
    {
        title: 'R',
        data: [
            {name: 'Romania', dialCode: '+40', code: 'RO'},
            {name: 'Russia', dialCode: '+7', code: 'RU'},
            {name: 'Rwanda', dialCode: '+250', code: 'RW'},
            {name: 'Reunion', dialCode: '+262', code: 'RE'},
        ],
    },
    {
        title: 'S',
        data: [
            {name: 'Saint Barthelemy', dialCode: '+590', code: 'BL'},
            {
                name: 'Saint Helena, Ascension and Tristan Da Cunha',
                dialCode: '+290',
                code: 'SH',
            },
            {name: 'Saint Helena', dialCode: '+247', code: 'SH'},
            {name: 'Saint Kitts and Nevis', dialCode: '+1869', code: 'KN'},
            {name: 'Saint Lucia', dialCode: '+1758', code: 'LC'},
            {name: 'Saint Martin', dialCode: '+590', code: 'MF'},
            {name: 'Saint Pierre and Miquelon', dialCode: '+508', code: 'PM'},
            {
                name: 'Saint Vincent and the Grenadines',
                dialCode: '+1784',
                code: 'VC',
            },
            {name: 'Samoa', dialCode: '+685', code: 'WS'},
            {name: 'San Marino', dialCode: '+378', code: 'SM'},
            {name: 'Sao Tome and Principe', dialCode: '+239', code: 'ST'},
            {name: 'Saudi Arabia', dialCode: '+966', code: 'SA'},
            {name: 'Senegal', dialCode: '+221', code: 'SN'},
            {name: 'Serbia', dialCode: '+381', code: 'RS'},
            {name: 'Seychelles', dialCode: '+248', code: 'SC'},
            {name: 'Sierra Leone', dialCode: '+232', code: 'SL'},
            {name: 'Singapore', dialCode: '+65', code: 'SG'},
            {name: 'Slovakia', dialCode: '+421', code: 'SK'},
            {name: 'Slovenia', dialCode: '+386', code: 'SI'},
            {name: 'Solomon Islands', dialCode: '+677', code: 'SB'},
            {name: 'Somalia', dialCode: '+252', code: 'SO'},
            {name: 'South Africa', dialCode: '+27', code: 'ZA'},
            {name: 'South Sudan', dialCode: '+211', code: 'SS'},
            {name: 'South Korea', dialCode: '+82', code: 'KR'},
            {name: 'South Georgia', dialCode: '+500', code: 'GS'},
            {name: 'Spain', dialCode: '+34', code: 'ES'},
            {name: 'Sri Lanka', dialCode: '+94', code: 'LK'},
            {name: 'Sudan', dialCode: '+249', code: 'SD'},
            {name: 'Suriname', dialCode: '+597', code: 'SR'},
            {name: 'Swaziland', dialCode: '+268', code: 'SZ'},
            {name: 'Sweden', dialCode: '+46', code: 'SE'},
            {name: 'Switzerland', dialCode: '+41', code: 'CH'},
            {name: 'Syria', dialCode: '+963', code: 'SY'},
        ],
    },
    {
        title: 'T',
        data: [
            {name: 'Taiwan', dialCode: '+886', code: 'TW'},
            {name: 'Tajikistan', dialCode: '+992', code: 'TJ'},
            {name: 'Tanzania', dialCode: '+255', code: 'TZ'},
            {name: 'Thailand', dialCode: '+66', code: 'TH'},
            {name: 'Timor-Leste', dialCode: '+670', code: 'TL'},
            {name: 'Togo', dialCode: '+228', code: 'TG'},
            {name: 'Tokelau', dialCode: '+690', code: 'TK'},
            {name: 'Tonga', dialCode: '+676', code: 'TO'},
            {name: 'Trinidad and Tobago', dialCode: '+1868', code: 'TT'},
            {name: 'Tunisia', dialCode: '+216', code: 'TN'},
            {name: 'Turkey', dialCode: '+90', code: 'TR'},
            {name: 'Turkmenistan', dialCode: '+993', code: 'TM'},
            {name: 'Turks and Caicos Islands', dialCode: '+1649', code: 'TC'},
            {name: 'Tuvalu', dialCode: '+688', code: 'TV'},
        ],
    },
    {
        title: 'U',
        data: [
            {name: 'Uganda', dialCode: '+256', code: 'UG'},
            {name: 'Ukraine', dialCode: '+380', code: 'UA'},
            {name: 'United Arab Emirates', dialCode: '+971', code: 'AE'},
            {name: 'United Kingdom', dialCode: '+44', code: 'GB'},
            {name: 'United States', dialCode: '+1', code: 'US'},
            {name: 'Uruguay', dialCode: '+598', code: 'UY'},
            {name: 'Uzbekistan', dialCode: '+998', code: 'UZ'},
        ],
    },
    {
        title: 'V',
        data: [
            {name: 'Vanuatu', dialCode: '+678', code: 'VU'},
            {name: 'Venezuela', dialCode: '+58', code: 'VE'},
            {name: 'Vietnam', dialCode: '+84', code: 'VN'},
            {name: 'British Virgin Islands', dialCode: '+1284', code: 'VG'},
            {name: 'U.S. Virgin Islands', dialCode: '+1340', code: 'VI'},
        ],
    },
    {
        title: 'W',
        data: [{name: 'Wallis and Futuna', dialCode: '+681', code: 'WF'}],
    },
    {title: 'Y', data: [{name: 'Yemen', dialCode: '+967', code: 'YE'}]},
    {
        title: 'Z',
        data: [
            {name: 'Zambia', dialCode: '+260', code: 'ZM'},
            {name: 'Zimbabwe', dialCode: '+263', code: 'ZW'},
        ],
    },
];
export const countriesNames = {
    '+93': {name: 'Afghanistan', code: 'AF'},
    '+355': {name: 'Albania', code: 'AL'},
    '+213': {name: 'Algeria', code: 'DZ'},
    '+1684': {name: 'American Samoa', code: 'AS'},
    '+376': {name: 'Andorra', code: 'AD'},
    '+244': {name: 'Angola', code: 'AO'},
    '+1264': {name: 'Anguilla', code: 'AI'},
    '+672': {name: 'Norfolk Island', code: 'NF'},
    '+1268': {name: 'Antigua and Barbuda', code: 'AG'},
    '+54': {name: 'Argentina', code: 'AR'},
    '+374': {name: 'Armenia', code: 'AM'},
    '+297': {name: 'Aruba', code: 'AW'},
    '+61': {name: 'Christmas Island', code: 'CX'},
    '+43': {name: 'Austria', code: 'AT'},
    '+994': {name: 'Azerbaijan', code: 'AZ'},
    '+1242': {name: 'Bahamas', code: 'BS'},
    '+973': {name: 'Bahrain', code: 'BH'},
    '+880': {name: 'Bangladesh', code: 'BD'},
    '+1246': {name: 'Barbados', code: 'BB'},
    '+375': {name: 'Belarus', code: 'BY'},
    '+32': {name: 'Belgium', code: 'BE'},
    '+501': {name: 'Belize', code: 'BZ'},
    '+229': {name: 'Benin', code: 'BJ'},
    '+1441': {name: 'Bermuda', code: 'BM'},
    '+975': {name: 'Bhutan', code: 'BT'},
    '+591': {name: 'Bolivia', code: 'BO'},
    '+387': {name: 'Bosnia and Herzegovina', code: 'BA'},
    '+267': {name: 'Botswana', code: 'BW'},
    '+47': {name: 'Norway', code: 'NO'},
    '+55': {name: 'Brazil', code: 'BR'},
    '+246': {name: 'British Indian Ocean Territory', code: 'IO'},
    '+673': {name: 'Brunei Darussalam', code: 'BN'},
    '+359': {name: 'Bulgaria', code: 'BG'},
    '+226': {name: 'Burkina Faso', code: 'BF'},
    '+257': {name: 'Burundi', code: 'BI'},
    '+855': {name: 'Cambodia', code: 'KH'},
    '+237': {name: 'Cameroon', code: 'CM'},
    '+1': {name: 'United States', code: 'US'},
    '+238': {name: 'Cape Verde', code: 'CV'},
    '+ 345': {name: 'Cayman Islands', code: 'KY'},
    '+236': {name: 'Central African Republic', code: 'CF'},
    '+235': {name: 'Chad', code: 'TD'},
    '+56': {name: 'Chile', code: 'CL'},
    '+86': {name: 'China', code: 'CN'},
    '+57': {name: 'Colombia', code: 'CO'},
    '+269': {name: 'Comoros', code: 'KM'},
    '+242': {name: 'Congo', code: 'CG'},
    '+243': {name: 'Congo, The Democratic Republic of the Congo', code: 'CD'},
    '+682': {name: 'Cook Islands', code: 'CK'},
    '+506': {name: 'Costa Rica', code: 'CR'},
    '+225': {name: "Cote d'Ivoire", code: 'CI'},
    '+385': {name: 'Croatia', code: 'HR'},
    '+53': {name: 'Cuba', code: 'CU'},
    '+357': {name: 'Cyprus', code: 'CY'},
    '+420': {name: 'Czech Republic', code: 'CZ'},
    '+45': {name: 'Denmark', code: 'DK'},
    '+253': {name: 'Djibouti', code: 'DJ'},
    '+1767': {name: 'Dominica', code: 'DM'},
    '+1849': {name: 'Dominican Republic', code: 'DO'},
    '+593': {name: 'Ecuador', code: 'EC'},
    '+20': {name: 'Egypt', code: 'EG'},
    '+503': {name: 'El Salvador', code: 'SV'},
    '+240': {name: 'Equatorial Guinea', code: 'GQ'},
    '+291': {name: 'Eritrea', code: 'ER'},
    '+372': {name: 'Estonia', code: 'EE'},
    '+251': {name: 'Ethiopia', code: 'ET'},
    '+500': {name: 'South Georgia and the South Sandwich Islands', code: 'GS'},
    '+298': {name: 'Faroe Islands', code: 'FO'},
    '+679': {name: 'Fiji', code: 'FJ'},
    '+358': {name: 'Finland', code: 'FI'},
    '+33': {name: 'France', code: 'FR'},
    '+594': {name: 'French Guiana', code: 'GF'},
    '+689': {name: 'French Polynesia', code: 'PF'},
    '+241': {name: 'Gabon', code: 'GA'},
    '+220': {name: 'Gambia', code: 'GM'},
    '+995': {name: 'Georgia', code: 'GE'},
    '+49': {name: 'Germany', code: 'DE'},
    '+233': {name: 'Ghana', code: 'GH'},
    '+350': {name: 'Gibraltar', code: 'GI'},
    '+30': {name: 'Greece', code: 'GR'},
    '+299': {name: 'Greenland', code: 'GL'},
    '+1473': {name: 'Grenada', code: 'GD'},
    '+590': {name: 'Saint Martin', code: 'MF'},
    '+1671': {name: 'Guam', code: 'GU'},
    '+502': {name: 'Guatemala', code: 'GT'},
    '+44': {name: 'United Kingdom', code: 'GB'},
    '+224': {name: 'Guinea', code: 'GN'},
    '+245': {name: 'Guinea-Bissau', code: 'GW'},
    '+592': {name: 'Guyana', code: 'GY'},
    '+509': {name: 'Haiti', code: 'HT'},
    '+504': {name: 'Honduras', code: 'HN'},
    '+852': {name: 'Hong Kong', code: 'HK'},
    '+36': {name: 'Hungary', code: 'HU'},
    '+354': {name: 'Iceland', code: 'IS'},
    '+91': {name: 'India', code: 'IN'},
    '+62': {name: 'Indonesia', code: 'ID'},
    '+98': {name: 'Iran', code: 'IR'},
    '+964': {name: 'Iraq', code: 'IQ'},
    '+353': {name: 'Ireland', code: 'IE'},
    '+972': {name: 'Israel', code: 'IL'},
    '+39': {name: 'Italy', code: 'IT'},
    '+1876': {name: 'Jamaica', code: 'JM'},
    '+81': {name: 'Japan', code: 'JP'},
    '+962': {name: 'Jordan', code: 'JO'},
    '+7': {name: 'Russia', code: 'RU'},
    '+254': {name: 'Kenya', code: 'KE'},
    '+686': {name: 'Kiribati', code: 'KI'},
    '+850': {name: "Korea, Democratic People's Republic of Korea", code: 'KP'},
    '+82': {name: 'Korea, Republic of South Korea', code: 'KR'},
    '+383': {name: 'Kosovo', code: 'XK'},
    '+965': {name: 'Kuwait', code: 'KW'},
    '+996': {name: 'Kyrgyzstan', code: 'KG'},
    '+856': {name: 'Laos', code: 'LA'},
    '+371': {name: 'Latvia', code: 'LV'},
    '+961': {name: 'Lebanon', code: 'LB'},
    '+266': {name: 'Lesotho', code: 'LS'},
    '+231': {name: 'Liberia', code: 'LR'},
    '+218': {name: 'Libya', code: 'LY'},
    '+423': {name: 'Liechtenstein', code: 'LI'},
    '+370': {name: 'Lithuania', code: 'LT'},
    '+352': {name: 'Luxembourg', code: 'LU'},
    '+853': {name: 'Macao', code: 'MO'},
    '+389': {name: 'Macedonia', code: 'MK'},
    '+261': {name: 'Madagascar', code: 'MG'},
    '+265': {name: 'Malawi', code: 'MW'},
    '+60': {name: 'Malaysia', code: 'MY'},
    '+960': {name: 'Maldives', code: 'MV'},
    '+223': {name: 'Mali', code: 'ML'},
    '+356': {name: 'Malta', code: 'MT'},
    '+692': {name: 'Marshall Islands', code: 'MH'},
    '+596': {name: 'Martinique', code: 'MQ'},
    '+222': {name: 'Mauritania', code: 'MR'},
    '+230': {name: 'Mauritius', code: 'MU'},
    '+262': {name: 'Reunion', code: 'RE'},
    '+52': {name: 'Mexico', code: 'MX'},
    '+691': {name: 'Micronesia', code: 'FM'},
    '+373': {name: 'Moldova', code: 'MD'},
    '+377': {name: 'Monaco', code: 'MC'},
    '+976': {name: 'Mongolia', code: 'MN'},
    '+382': {name: 'Montenegro', code: 'ME'},
    '+1664': {name: 'Montserrat', code: 'MS'},
    '+212': {name: 'Morocco', code: 'MA'},
    '+258': {name: 'Mozambique', code: 'MZ'},
    '+95': {name: 'Myanmar', code: 'MM'},
    '+264': {name: 'Namibia', code: 'NA'},
    '+674': {name: 'Nauru', code: 'NR'},
    '+977': {name: 'Nepal', code: 'NP'},
    '+31': {name: 'Netherlands', code: 'NL'},
    '+599': {name: 'Netherlands Antilles', code: 'AN'},
    '+687': {name: 'New Caledonia', code: 'NC'},
    '+64': {name: 'Pitcairn', code: 'PN'},
    '+505': {name: 'Nicaragua', code: 'NI'},
    '+227': {name: 'Niger', code: 'NE'},
    '+234': {name: 'Nigeria', code: 'NG'},
    '+683': {name: 'Niue', code: 'NU'},
    '+1670': {name: 'Northern Mariana Islands', code: 'MP'},
    '+968': {name: 'Oman', code: 'OM'},
    '+92': {name: 'Pakistan', code: 'PK'},
    '+680': {name: 'Palau', code: 'PW'},
    '+970': {name: 'Palestine', code: 'PS'},
    '+507': {name: 'Panama', code: 'PA'},
    '+675': {name: 'Papua New Guinea', code: 'PG'},
    '+595': {name: 'Paraguay', code: 'PY'},
    '+51': {name: 'Peru', code: 'PE'},
    '+63': {name: 'Philippines', code: 'PH'},
    '+48': {name: 'Poland', code: 'PL'},
    '+351': {name: 'Portugal', code: 'PT'},
    '+1939': {name: 'Puerto Rico', code: 'PR'},
    '+974': {name: 'Qatar', code: 'QA'},
    '+40': {name: 'Romania', code: 'RO'},
    '+250': {name: 'Rwanda', code: 'RW'},
    '+290': {name: 'Saint Helena, Ascension and Tristan Da Cunha', code: 'SH'},
    '+247': {name: 'Saint Helena', code: 'SH'},
    '+1869': {name: 'Saint Kitts and Nevis', code: 'KN'},
    '+1758': {name: 'Saint Lucia', code: 'LC'},
    '+508': {name: 'Saint Pierre and Miquelon', code: 'PM'},
    '+1784': {name: 'Saint Vincent and the Grenadines', code: 'VC'},
    '+685': {name: 'Samoa', code: 'WS'},
    '+378': {name: 'San Marino', code: 'SM'},
    '+239': {name: 'Sao Tome and Principe', code: 'ST'},
    '+966': {name: 'Saudi Arabia', code: 'SA'},
    '+221': {name: 'Senegal', code: 'SN'},
    '+381': {name: 'Serbia', code: 'RS'},
    '+248': {name: 'Seychelles', code: 'SC'},
    '+232': {name: 'Sierra Leone', code: 'SL'},
    '+65': {name: 'Singapore', code: 'SG'},
    '+421': {name: 'Slovakia', code: 'SK'},
    '+386': {name: 'Slovenia', code: 'SI'},
    '+677': {name: 'Solomon Islands', code: 'SB'},
    '+252': {name: 'Somalia', code: 'SO'},
    '+27': {name: 'South Africa', code: 'ZA'},
    '+211': {name: 'South Sudan', code: 'SS'},
    '+34': {name: 'Spain', code: 'ES'},
    '+94': {name: 'Sri Lanka', code: 'LK'},
    '+249': {name: 'Sudan', code: 'SD'},
    '+597': {name: 'Suriname', code: 'SR'},
    '+268': {name: 'Swaziland', code: 'SZ'},
    '+46': {name: 'Sweden', code: 'SE'},
    '+41': {name: 'Switzerland', code: 'CH'},
    '+963': {name: 'Syria', code: 'SY'},
    '+886': {name: 'Taiwan', code: 'TW'},
    '+992': {name: 'Tajikistan', code: 'TJ'},
    '+255': {name: 'Tanzania', code: 'TZ'},
    '+66': {name: 'Thailand', code: 'TH'},
    '+670': {name: 'Timor-Leste', code: 'TL'},
    '+228': {name: 'Togo', code: 'TG'},
    '+690': {name: 'Tokelau', code: 'TK'},
    '+676': {name: 'Tonga', code: 'TO'},
    '+1868': {name: 'Trinidad and Tobago', code: 'TT'},
    '+216': {name: 'Tunisia', code: 'TN'},
    '+90': {name: 'Turkey', code: 'TR'},
    '+993': {name: 'Turkmenistan', code: 'TM'},
    '+1649': {name: 'Turks and Caicos Islands', code: 'TC'},
    '+688': {name: 'Tuvalu', code: 'TV'},
    '+256': {name: 'Uganda', code: 'UG'},
    '+380': {name: 'Ukraine', code: 'UA'},
    '+971': {name: 'United Arab Emirates', code: 'AE'},
    '+598': {name: 'Uruguay', code: 'UY'},
    '+998': {name: 'Uzbekistan', code: 'UZ'},
    '+678': {name: 'Vanuatu', code: 'VU'},
    '+58': {name: 'Venezuela, Bolivarian Republic of Venezuela', code: 'VE'},
    '+84': {name: 'Vietnam', code: 'VN'},
    '+1284': {name: 'British Virgin Islands', code: 'VG'},
    '+1340': {name: 'U.S. Virgin Islands', code: 'VI'},
    '+681': {name: 'Wallis and Futuna', code: 'WF'},
    '+967': {name: 'Yemen', code: 'YE'},
    '+260': {name: 'Zambia', code: 'ZM'},
    '+263': {name: 'Zimbabwe', code: 'ZW'},
};
export const countries = [
    {name: 'Afghanistan', dialCode: '+93', code: 'AF'},
    {name: 'Albania', dialCode: '+355', code: 'AL'},
    {name: 'Algeria', dialCode: '+213', code: 'DZ'},
    {name: 'American Samoa', dialCode: '+1684', code: 'AS'},
    {name: 'Andorra', dialCode: '+376', code: 'AD'},
    {name: 'Angola', dialCode: '+244', code: 'AO'},
    {name: 'Anguilla', dialCode: '+1264', code: 'AI'},
    {name: 'Antarctica', dialCode: '+672', code: 'AQ'},
    {name: 'Antigua and Barbuda', dialCode: '+1268', code: 'AG'},
    {name: 'Argentina', dialCode: '+54', code: 'AR'},
    {name: 'Armenia', dialCode: '+374', code: 'AM'},
    {name: 'Aruba', dialCode: '+297', code: 'AW'},
    {name: 'Australia', dialCode: '+61', code: 'AU'},
    {name: 'Austria', dialCode: '+43', code: 'AT'},
    {name: 'Azerbaijan', dialCode: '+994', code: 'AZ'},
    {name: 'Bahamas', dialCode: '+1242', code: 'BS'},
    {name: 'Bahrain', dialCode: '+973', code: 'BH'},
    {name: 'Bangladesh', dialCode: '+880', code: 'BD'},
    {name: 'Barbados', dialCode: '+1246', code: 'BB'},
    {name: 'Belarus', dialCode: '+375', code: 'BY'},
    {name: 'Belgium', dialCode: '+32', code: 'BE'},
    {name: 'Belize', dialCode: '+501', code: 'BZ'},
    {name: 'Benin', dialCode: '+229', code: 'BJ'},
    {name: 'Bermuda', dialCode: '+1441', code: 'BM'},
    {name: 'Bhutan', dialCode: '+975', code: 'BT'},
    {name: 'Bolivia', dialCode: '+591', code: 'BO'},
    {name: 'Bosnia and Herzegovina', dialCode: '+387', code: 'BA'},
    {name: 'Botswana', dialCode: '+267', code: 'BW'},
    {name: 'Bouvet Island', dialCode: '+47', code: 'BV'},
    {name: 'Brazil', dialCode: '+55', code: 'BR'},
    {name: 'British Indian Ocean Territory', dialCode: '+246', code: 'IO'},
    {name: 'Brunei Darussalam', dialCode: '+673', code: 'BN'},
    {name: 'Bulgaria', dialCode: '+359', code: 'BG'},
    {name: 'Burkina Faso', dialCode: '+226', code: 'BF'},
    {name: 'Burundi', dialCode: '+257', code: 'BI'},
    {name: 'Cambodia', dialCode: '+855', code: 'KH'},
    {name: 'Cameroon', dialCode: '+237', code: 'CM'},
    {name: 'Canada', dialCode: '+1', code: 'CA'},
    {name: 'Cape Verde', dialCode: '+238', code: 'CV'},
    {name: 'Cayman Islands', dialCode: '+ 345', code: 'KY'},
    {name: 'Central African Republic', dialCode: '+236', code: 'CF'},
    {name: 'Chad', dialCode: '+235', code: 'TD'},
    {name: 'Chile', dialCode: '+56', code: 'CL'},
    {name: 'China', dialCode: '+86', code: 'CN'},
    {name: 'Christmas Island', dialCode: '+61', code: 'CX'},
    {name: 'Colombia', dialCode: '+57', code: 'CO'},
    {name: 'Comoros', dialCode: '+269', code: 'KM'},
    {name: 'Congo', dialCode: '+242', code: 'CG'},
    {
        name: 'Congo, The Democratic Republic of the Congo',
        dialCode: '+243',
        code: 'CD',
    },
    {name: 'Cook Islands', dialCode: '+682', code: 'CK'},
    {name: 'Costa Rica', dialCode: '+506', code: 'CR'},
    {name: "Cote d'Ivoire", dialCode: '+225', code: 'CI'},
    {name: 'Croatia', dialCode: '+385', code: 'HR'},
    {name: 'Cuba', dialCode: '+53', code: 'CU'},
    {name: 'Cyprus', dialCode: '+357', code: 'CY'},
    {name: 'Czech Republic', dialCode: '+420', code: 'CZ'},
    {name: 'Denmark', dialCode: '+45', code: 'DK'},
    {name: 'Djibouti', dialCode: '+253', code: 'DJ'},
    {name: 'Dominica', dialCode: '+1767', code: 'DM'},
    {name: 'Dominican Republic', dialCode: '+1849', code: 'DO'},
    {name: 'Ecuador', dialCode: '+593', code: 'EC'},
    {name: 'Egypt', dialCode: '+20', code: 'EG'},
    {name: 'El Salvador', dialCode: '+503', code: 'SV'},
    {name: 'Equatorial Guinea', dialCode: '+240', code: 'GQ'},
    {name: 'Eritrea', dialCode: '+291', code: 'ER'},
    {name: 'Estonia', dialCode: '+372', code: 'EE'},
    {name: 'Ethiopia', dialCode: '+251', code: 'ET'},
    {name: 'Falkland Islands', dialCode: '+500', code: 'FK'},
    {name: 'Faroe Islands', dialCode: '+298', code: 'FO'},
    {name: 'Fiji', dialCode: '+679', code: 'FJ'},
    {name: 'Finland', dialCode: '+358', code: 'FI'},
    {name: 'France', dialCode: '+33', code: 'FR'},
    {name: 'French Guiana', dialCode: '+594', code: 'GF'},
    {name: 'French Polynesia', dialCode: '+689', code: 'PF'},
    {name: 'Gabon', dialCode: '+241', code: 'GA'},
    {name: 'Gambia', dialCode: '+220', code: 'GM'},
    {name: 'Georgia', dialCode: '+995', code: 'GE'},
    {name: 'Germany', dialCode: '+49', code: 'DE'},
    {name: 'Ghana', dialCode: '+233', code: 'GH'},
    {name: 'Gibraltar', dialCode: '+350', code: 'GI'},
    {name: 'Greece', dialCode: '+30', code: 'GR'},
    {name: 'Greenland', dialCode: '+299', code: 'GL'},
    {name: 'Grenada', dialCode: '+1473', code: 'GD'},
    {name: 'Guadeloupe', dialCode: '+590', code: 'GP'},
    {name: 'Guam', dialCode: '+1671', code: 'GU'},
    {name: 'Guatemala', dialCode: '+502', code: 'GT'},
    {name: 'Guernsey', dialCode: '+44', code: 'GG'},
    {name: 'Guinea', dialCode: '+224', code: 'GN'},
    {name: 'Guinea-Bissau', dialCode: '+245', code: 'GW'},
    {name: 'Guyana', dialCode: '+592', code: 'GY'},
    {name: 'Haiti', dialCode: '+509', code: 'HT'},
    {name: 'Honduras', dialCode: '+504', code: 'HN'},
    {name: 'Hong Kong', dialCode: '+852', code: 'HK'},
    {name: 'Hungary', dialCode: '+36', code: 'HU'},
    {name: 'Iceland', dialCode: '+354', code: 'IS'},
    {name: 'India', dialCode: '+91', code: 'IN'},
    {name: 'Indonesia', dialCode: '+62', code: 'ID'},
    {name: 'Iran', dialCode: '+98', code: 'IR'},
    {name: 'Iraq', dialCode: '+964', code: 'IQ'},
    {name: 'Ireland', dialCode: '+353', code: 'IE'},
    {name: 'Isle of Man', dialCode: '+44', code: 'IM'},
    {name: 'Israel', dialCode: '+972', code: 'IL'},
    {name: 'Italy', dialCode: '+39', code: 'IT'},
    {name: 'Jamaica', dialCode: '+1876', code: 'JM'},
    {name: 'Japan', dialCode: '+81', code: 'JP'},
    {name: 'Jersey', dialCode: '+44', code: 'JE'},
    {name: 'Jordan', dialCode: '+962', code: 'JO'},
    {name: 'Kazakhstan', dialCode: '+7', code: 'KZ'},
    {name: 'Kenya', dialCode: '+254', code: 'KE'},
    {name: 'Kiribati', dialCode: '+686', code: 'KI'},
    {
        name: "Korea, Democratic People's Republic of Korea",
        dialCode: '+850',
        code: 'KP',
    },
    {name: 'Korea, Republic of South Korea', dialCode: '+82', code: 'KR'},
    {name: 'Kosovo', dialCode: '+383', code: 'XK'},
    {name: 'Kuwait', dialCode: '+965', code: 'KW'},
    {name: 'Kyrgyzstan', dialCode: '+996', code: 'KG'},
    {name: 'Laos', dialCode: '+856', code: 'LA'},
    {name: 'Latvia', dialCode: '+371', code: 'LV'},
    {name: 'Lebanon', dialCode: '+961', code: 'LB'},
    {name: 'Lesotho', dialCode: '+266', code: 'LS'},
    {name: 'Liberia', dialCode: '+231', code: 'LR'},
    {name: 'Libya', dialCode: '+218', code: 'LY'},
    {name: 'Liechtenstein', dialCode: '+423', code: 'LI'},
    {name: 'Lithuania', dialCode: '+370', code: 'LT'},
    {name: 'Luxembourg', dialCode: '+352', code: 'LU'},
    {name: 'Macao', dialCode: '+853', code: 'MO'},
    {name: 'Macedonia', dialCode: '+389', code: 'MK'},
    {name: 'Madagascar', dialCode: '+261', code: 'MG'},
    {name: 'Malawi', dialCode: '+265', code: 'MW'},
    {name: 'Malaysia', dialCode: '+60', code: 'MY'},
    {name: 'Maldives', dialCode: '+960', code: 'MV'},
    {name: 'Mali', dialCode: '+223', code: 'ML'},
    {name: 'Malta', dialCode: '+356', code: 'MT'},
    {name: 'Marshall Islands', dialCode: '+692', code: 'MH'},
    {name: 'Martinique', dialCode: '+596', code: 'MQ'},
    {name: 'Mauritania', dialCode: '+222', code: 'MR'},
    {name: 'Mauritius', dialCode: '+230', code: 'MU'},
    {name: 'Mayotte', dialCode: '+262', code: 'YT'},
    {name: 'Mexico', dialCode: '+52', code: 'MX'},
    {name: 'Micronesia', dialCode: '+691', code: 'FM'},
    {name: 'Moldova', dialCode: '+373', code: 'MD'},
    {name: 'Monaco', dialCode: '+377', code: 'MC'},
    {name: 'Mongolia', dialCode: '+976', code: 'MN'},
    {name: 'Montenegro', dialCode: '+382', code: 'ME'},
    {name: 'Montserrat', dialCode: '+1664', code: 'MS'},
    {name: 'Morocco', dialCode: '+212', code: 'MA'},
    {name: 'Mozambique', dialCode: '+258', code: 'MZ'},
    {name: 'Myanmar', dialCode: '+95', code: 'MM'},
    {name: 'Namibia', dialCode: '+264', code: 'NA'},
    {name: 'Nauru', dialCode: '+674', code: 'NR'},
    {name: 'Nepal', dialCode: '+977', code: 'NP'},
    {name: 'Netherlands', dialCode: '+31', code: 'NL'},
    {name: 'Netherlands Antilles', dialCode: '+599', code: 'AN'},
    {name: 'New Caledonia', dialCode: '+687', code: 'NC'},
    {name: 'New Zealand', dialCode: '+64', code: 'NZ'},
    {name: 'Nicaragua', dialCode: '+505', code: 'NI'},
    {name: 'Niger', dialCode: '+227', code: 'NE'},
    {name: 'Nigeria', dialCode: '+234', code: 'NG'},
    {name: 'Niue', dialCode: '+683', code: 'NU'},
    {name: 'Norfolk Island', dialCode: '+672', code: 'NF'},
    {name: 'Northern Mariana Islands', dialCode: '+1670', code: 'MP'},
    {name: 'Norway', dialCode: '+47', code: 'NO'},
    {name: 'Oman', dialCode: '+968', code: 'OM'},
    {name: 'Pakistan', dialCode: '+92', code: 'PK'},
    {name: 'Palau', dialCode: '+680', code: 'PW'},
    {name: 'Palestine', dialCode: '+970', code: 'PS'},
    {name: 'Panama', dialCode: '+507', code: 'PA'},
    {name: 'Papua New Guinea', dialCode: '+675', code: 'PG'},
    {name: 'Paraguay', dialCode: '+595', code: 'PY'},
    {name: 'Peru', dialCode: '+51', code: 'PE'},
    {name: 'Philippines', dialCode: '+63', code: 'PH'},
    {name: 'Pitcairn', dialCode: '+64', code: 'PN'},
    {name: 'Poland', dialCode: '+48', code: 'PL'},
    {name: 'Portugal', dialCode: '+351', code: 'PT'},
    {name: 'Puerto Rico', dialCode: '+1939', code: 'PR'},
    {name: 'Qatar', dialCode: '+974', code: 'QA'},
    {name: 'Romania', dialCode: '+40', code: 'RO'},
    {name: 'Russia', dialCode: '+7', code: 'RU'},
    {name: 'Rwanda', dialCode: '+250', code: 'RW'},
    {name: 'Reunion', dialCode: '+262', code: 'RE'},
    {name: 'Saint Barthelemy', dialCode: '+590', code: 'BL'},
    {
        name: 'Saint Helena, Ascension and Tristan Da Cunha',
        dialCode: '+290',
        code: 'SH',
    },
    {name: 'Saint Helena', dialCode: '+247', code: 'SH'},
    {name: 'Saint Kitts and Nevis', dialCode: '+1869', code: 'KN'},
    {name: 'Saint Lucia', dialCode: '+1758', code: 'LC'},
    {name: 'Saint Martin', dialCode: '+590', code: 'MF'},
    {name: 'Saint Pierre and Miquelon', dialCode: '+508', code: 'PM'},
    {name: 'Saint Vincent and the Grenadines', dialCode: '+1784', code: 'VC'},
    {name: 'Samoa', dialCode: '+685', code: 'WS'},
    {name: 'San Marino', dialCode: '+378', code: 'SM'},
    {name: 'Sao Tome and Principe', dialCode: '+239', code: 'ST'},
    {name: 'Saudi Arabia', dialCode: '+966', code: 'SA'},
    {name: 'Senegal', dialCode: '+221', code: 'SN'},
    {name: 'Serbia', dialCode: '+381', code: 'RS'},
    {name: 'Seychelles', dialCode: '+248', code: 'SC'},
    {name: 'Sierra Leone', dialCode: '+232', code: 'SL'},
    {name: 'Singapore', dialCode: '+65', code: 'SG'},
    {name: 'Slovakia', dialCode: '+421', code: 'SK'},
    {name: 'Slovenia', dialCode: '+386', code: 'SI'},
    {name: 'Solomon Islands', dialCode: '+677', code: 'SB'},
    {name: 'Somalia', dialCode: '+252', code: 'SO'},
    {name: 'South Africa', dialCode: '+27', code: 'ZA'},
    {name: 'South Sudan', dialCode: '+211', code: 'SS'},
    {
        name: 'South Georgia and the South Sandwich Islands',
        dialCode: '+500',
        code: 'GS',
    },
    {name: 'Spain', dialCode: '+34', code: 'ES'},
    {name: 'Sri Lanka', dialCode: '+94', code: 'LK'},
    {name: 'Sudan', dialCode: '+249', code: 'SD'},
    {name: 'Suriname', dialCode: '+597', code: 'SR'},
    {name: 'Swaziland', dialCode: '+268', code: 'SZ'},
    {name: 'Sweden', dialCode: '+46', code: 'SE'},
    {name: 'Switzerland', dialCode: '+41', code: 'CH'},
    {name: 'Syria', dialCode: '+963', code: 'SY'},
    {name: 'Taiwan', dialCode: '+886', code: 'TW'},
    {name: 'Tajikistan', dialCode: '+992', code: 'TJ'},
    {name: 'Tanzania', dialCode: '+255', code: 'TZ'},
    {name: 'Thailand', dialCode: '+66', code: 'TH'},
    {name: 'Timor-Leste', dialCode: '+670', code: 'TL'},
    {name: 'Togo', dialCode: '+228', code: 'TG'},
    {name: 'Tokelau', dialCode: '+690', code: 'TK'},
    {name: 'Tonga', dialCode: '+676', code: 'TO'},
    {name: 'Trinidad and Tobago', dialCode: '+1868', code: 'TT'},
    {name: 'Tunisia', dialCode: '+216', code: 'TN'},
    {name: 'Turkey', dialCode: '+90', code: 'TR'},
    {name: 'Turkmenistan', dialCode: '+993', code: 'TM'},
    {name: 'Turks and Caicos Islands', dialCode: '+1649', code: 'TC'},
    {name: 'Tuvalu', dialCode: '+688', code: 'TV'},
    {name: 'Uganda', dialCode: '+256', code: 'UG'},
    {name: 'Ukraine', dialCode: '+380', code: 'UA'},
    {name: 'United Arab Emirates', dialCode: '+971', code: 'AE'},
    {name: 'United Kingdom', dialCode: '+44', code: 'GB'},
    {name: 'United States', dialCode: '+1', code: 'US'},
    {name: 'Uruguay', dialCode: '+598', code: 'UY'},
    {name: 'Uzbekistan', dialCode: '+998', code: 'UZ'},
    {name: 'Vanuatu', dialCode: '+678', code: 'VU'},
    {
        name: 'Venezuela, Bolivarian Republic of Venezuela',
        dialCode: '+58',
        code: 'VE',
    },
    {name: 'Vietnam', dialCode: '+84', code: 'VN'},
    {name: 'British Virgin Islands', dialCode: '+1284', code: 'VG'},
    {name: 'U.S. Virgin Islands', dialCode: '+1340', code: 'VI'},
    {name: 'Wallis and Futuna', dialCode: '+681', code: 'WF'},
    {name: 'Yemen', dialCode: '+967', code: 'YE'},
    {name: 'Zambia', dialCode: '+260', code: 'ZM'},
    {name: 'Zimbabwe', dialCode: '+263', code: 'ZW'},
];
